services:
  postgres:
    image: postgres:14-alpine
    container_name: ride_share_postgres
    ports:
      - "3306:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ride_sharing_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ride_sharing_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: ride_share_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ride_sharing_network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: ride_share_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - ride_sharing_network

  redis:
    image: redis:6.2-alpine
    container_name: ride_share_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ride_sharing_network

  zipkin:
    image: openzipkin/zipkin:2
    container_name: ride_share_zipkin
    ports:
      - "9411:9411"
    networks:
      - ride_sharing_network

volumes:
  postgres_data:
  redis_data:


networks:
  ride_sharing_network:
    driver: bridge
